const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

function toPascalCase(str) {
  return str.replace(/(?:^|_)([a-z])/g, (_, g) => g.toUpperCase());
}

const rootDir = path.resolve(__dirname, '..');
const protoDir = path.join(rootDir, 'Protos');
const outDir = path.join(rootDir, 'src', 'generated');

console.log('--- Generating gRPC Code from Protobuf files ---');

// 1. Clean & create output directory
if (fs.existsSync(outDir)) {
  fs.rmSync(outDir, { recursive: true, force: true });
}
fs.mkdirSync(outDir, { recursive: true });

// 2. Find all .proto files
const files = fs
  .readdirSync(protoDir)
  .filter((file) => file.endsWith('.proto'))
  .map((file) => path.join('Protos', file));

if (files.length === 0) {
  console.error('No .proto files found in Protos directory!');
  process.exit(1);
}

console.log(`Found ${files.length} proto files:`, files);

// 3. Construct the protoc command
const filesArg = files.join(' ');
const command = `npx protoc --ts_out src/generated --proto_path . ${filesArg}`;

console.log(`Running: ${command}`);

try {
  execSync(command, { cwd: rootDir, stdio: 'inherit' });
  console.log(
    '✅ gRPC client code generated successfully under src/generated/'
  );

  // 4. Generate src/generated/wrapped-clients.ts (Compile-Time Wrappers)
  console.log('Generating wrapped-clients.ts...');
  const clientFiles = fs
    .readdirSync(path.join(outDir, 'Protos'))
    .filter((file) => file.endsWith('.client.ts'));

  let wrappedClientsContent = `// @generated by scripts/generate-proto.js - DO NOT EDIT MANUALLY
import { UnaryCall } from "@protobuf-ts/runtime-rpc";

`;

  // Add imports for raw clients
  clientFiles.forEach((file) => {
    const name = path.basename(file, '.client.ts');
    const serviceClientName = `${toPascalCase(name)}ServiceClient`;
    wrappedClientsContent += `import { ${serviceClientName} } from "./Protos/${name}.client";\n`;
  });

  wrappedClientsContent += `
type UnwrapUnaryCall<T> = T extends (...args: any[]) => UnaryCall<any, infer O>
  ? O
  : never;
`;

  // Mappings for backward compatibility
  const MAPPINGS = {
    blog: {
      getByQuery: 'getBlogsByQuery',
      getBySlug: 'getBlogDetail',
    },
    product: {
      getByQuery: 'getProductsByQuery',
      getBySlug: 'getProductDetail',
    },
  };

  clientFiles.forEach((file) => {
    const name = path.basename(file, '.client.ts');
    const serviceClientName = `${toPascalCase(name)}ServiceClient`;
    const wrappedName = `Wrapped${serviceClientName}`;

    const clientPath = path.join(outDir, 'Protos', file);
    const clientContent = fs.readFileSync(clientPath, 'utf-8');

    // Find interface contents to extract methods
    const interfaceName = `I${serviceClientName}`;
    const interfaceRegex = new RegExp(
      `export interface ${interfaceName} \\{([\\s\\S]*?)\\}`
    );
    const interfaceMatch = clientContent.match(interfaceRegex);
    if (!interfaceMatch) return;

    const methodsBlock = interfaceMatch[1];
    const methodRegex = /(\w+)\(input: /g;
    let match;
    const methods = [];
    while ((match = methodRegex.exec(methodsBlock)) !== null) {
      methods.push(match[1]);
    }

    wrappedClientsContent += `\nexport class ${wrappedName} {\n`;
    wrappedClientsContent += `  constructor(private readonly client: ${serviceClientName}) {}\n`;

    // Generate wrapped methods
    methods.forEach((method) => {
      wrappedClientsContent += `
  async ${method}(
    input: Parameters<${serviceClientName}['${method}']>[0],
    options?: Parameters<${serviceClientName}['${method}']>[1]
  ): Promise<UnwrapUnaryCall<${serviceClientName}['${method}']>> {
    return this.client.${method}(input, options).response;
  }\n`;
    });

    // Generate mapped methods if any
    const mappings = MAPPINGS[name];
    if (mappings) {
      Object.entries(mappings).forEach(([alias, targetMethod]) => {
        wrappedClientsContent += `
  async ${alias}(
    input: Parameters<${serviceClientName}['${targetMethod}']>[0],
    options?: Parameters<${serviceClientName}['${targetMethod}']>[1]
  ): Promise<UnwrapUnaryCall<${serviceClientName}['${targetMethod}']>> {
    return this.${targetMethod}(input, options);
  }\n`;
      });
    }

    wrappedClientsContent += `}\n`;
  });

  fs.writeFileSync(
    path.join(outDir, 'wrapped-clients.ts'),
    wrappedClientsContent,
    'utf-8'
  );
  console.log('✅ Generated src/generated/wrapped-clients.ts');

  // 5. Generate/Update src/index.ts to automatically export all generated files and their client types
  const indexFilePath = path.join(rootDir, 'src', 'index.ts');
  let indexContent = `// Core SDK Client & Lỗi gRPC
export { OptiFlowGrpcSDK, GrpcSDKConfig, grpcSDK, RpcError, WrappedClient } from './client';
export * from './criteria';

// Type của Wrapped Clients
export type * from './generated/wrapped-clients';

// Type DTO (Request/Response) - Tránh rác runtime
`;

  const protoNames = files.map((file) => path.basename(file, '.proto')).sort();

  protoNames.forEach((name) => {
    indexContent += `export type * from './generated/Protos/${name}';\n`;
  });

  indexContent += `\n// Type của Service Clients\n`;
  protoNames.forEach((name) => {
    const clientPath = path.join(outDir, 'Protos', `${name}.client.ts`);
    if (fs.existsSync(clientPath)) {
      indexContent += `export type * from './generated/Protos/${name}.client';\n`;
    }
  });

  indexContent += `\n// SEO Helpers & Components\n`;
  indexContent += `export * from './seo/seoHelper';\n`;
  indexContent += `export * from './seo/sitemap-helper';\n`;
  indexContent += `export * from './seo/generateMetadata';\n`;
  indexContent += `export * from './seo/SeoScripts';\n`;

  fs.writeFileSync(indexFilePath, indexContent, 'utf-8');
  console.log('✅ Generated src/index.ts with exports');
} catch (error) {
  console.error('❌ Failed to generate gRPC client code:', error);
  process.exit(1);
}
